-- Delete existing seed tasks to avoid duplicates on re-run
DELETE FROM task_tracking WHERE user_id = 'seed';

INSERT INTO task_tracking (user_id, category, task_name, dosha) VALUES
-- VATA
('seed', 'diet', 'Drink warm water on waking', 'vata'),
('seed', 'diet', 'Eat a warm, cooked breakfast', 'vata'),
('seed', 'diet', 'Add ghee to one meal', 'vata'),
('seed', 'diet', 'Sip ginger-fennel tea midday', 'vata'),
('seed', 'diet', 'Have dinner before 7:30 PM', 'vata'),
('seed', 'yoga', 'Practice slow cat-cow for 5 minutes', 'vata'),
('seed', 'yoga', 'Hold child pose with deep breathing', 'vata'),
('seed', 'yoga', 'Do 8 gentle seated twists', 'vata'),
('seed', 'yoga', 'Practice alternate nostril breathing 5 minutes', 'vata'),
('seed', 'yoga', 'End with 7 minutes guided relaxation', 'vata'),
('seed', 'routine', 'Wake and sleep at consistent times', 'vata'),
('seed', 'routine', 'Do warm sesame oil self-massage', 'vata'),
('seed', 'routine', 'Take short grounding breaks every 3 hours', 'vata'),
('seed', 'routine', 'Keep evening screen-free for 30 minutes', 'vata'),
('seed', 'routine', 'Sleep before 10:30 PM', 'vata'),

-- PITTA
('seed', 'diet', 'Start day with room-temperature water', 'pitta'),
('seed', 'diet', 'Include cucumber or mint at lunch', 'pitta'),
('seed', 'diet', 'Avoid very spicy foods today', 'pitta'),
('seed', 'diet', 'Drink coriander-fennel tea afternoon', 'pitta'),
('seed', 'diet', 'Finish dinner at least 3 hours before sleep', 'pitta'),
('seed', 'yoga', 'Practice moon salutations for 10 minutes', 'pitta'),
('seed', 'yoga', 'Hold forward fold for 8 breaths', 'pitta'),
('seed', 'yoga', 'Do gentle spinal twists slowly', 'pitta'),
('seed', 'yoga', 'Practice sheetali breathing for 5 minutes', 'pitta'),
('seed', 'yoga', 'End with cooling meditation 7 minutes', 'pitta'),
('seed', 'routine', 'Begin morning with 5 minutes quiet breathing', 'pitta'),
('seed', 'routine', 'Take a midday cooling break outdoors', 'pitta'),
('seed', 'routine', 'Avoid overworking past sunset', 'pitta'),
('seed', 'routine', 'Do a relaxing walk after dinner', 'pitta'),
('seed', 'routine', 'Sleep before 10:30 PM', 'pitta'),

-- KAPHA
('seed', 'diet', 'Drink warm lemon water on waking', 'kapha'),
('seed', 'diet', 'Keep breakfast light and warm', 'kapha'),
('seed', 'diet', 'Use ginger and black pepper in lunch', 'kapha'),
('seed', 'diet', 'Avoid sugary snacks between meals', 'kapha'),
('seed', 'diet', 'Take an early, light dinner', 'kapha'),
('seed', 'yoga', 'Do 6 rounds sun salutations', 'kapha'),
('seed', 'yoga', 'Hold chair pose for 5 breaths', 'kapha'),
('seed', 'yoga', 'Practice brisk standing flow 12 minutes', 'kapha'),
('seed', 'yoga', 'Do kapalabhati breathing 3 rounds', 'kapha'),
('seed', 'yoga', 'Take a 20-minute evening walk', 'kapha'),
('seed', 'routine', 'Wake before 6:30 AM', 'kapha'),
('seed', 'routine', 'Start day with dry brushing', 'kapha'),
('seed', 'routine', 'Take movement breaks every 2 hours', 'kapha'),
('seed', 'routine', 'Avoid daytime naps', 'kapha'),
('seed', 'routine', 'Do 10 minutes energizing breathing evening', 'kapha'),

-- VATA+PITTA
('seed', 'diet', 'Drink lukewarm water with a hint of mint', 'vata+pitta'),
('seed', 'diet', 'Eat a nourishing but not overly spicy lunch', 'vata+pitta'),
('seed', 'diet', 'Include sweet juicy fruits in the afternoon', 'vata+pitta'),
('seed', 'diet', 'Use coriander and fennel in cooking', 'vata+pitta'),
('seed', 'diet', 'Have an early, calming dinner', 'vata+pitta'),
('seed', 'yoga', 'Practice grounding standing poses', 'vata+pitta'),
('seed', 'yoga', 'Hold seated forward folds', 'vata+pitta'),
('seed', 'yoga', 'Do gentle side stretches', 'vata+pitta'),
('seed', 'yoga', 'Practice alternate nostril breathing to balance', 'vata+pitta'),
('seed', 'yoga', 'End with a long shavasana', 'vata+pitta'),
('seed', 'routine', 'Wake up at a consistent time', 'vata+pitta'),
('seed', 'routine', 'Massage feet with warm oil before bed', 'vata+pitta'),
('seed', 'routine', 'Avoid rushing during the workday', 'vata+pitta'),
('seed', 'routine', 'Take a peaceful evening walk', 'vata+pitta'),
('seed', 'routine', 'Dim lights 1 hour before sleep', 'vata+pitta'),

-- PITTA+KAPHA
('seed', 'diet', 'Drink room-temperature lemon water', 'pitta+kapha'),
('seed', 'diet', 'Eat a light, astringent lunch', 'pitta+kapha'),
('seed', 'diet', 'Avoid deep-fried and heavy sweet foods', 'pitta+kapha'),
('seed', 'diet', 'Drink bitter or astringent herbal teas', 'pitta+kapha'),
('seed', 'diet', 'Keep dinner very light and early', 'pitta+kapha'),
('seed', 'yoga', 'Do an active but cooling yoga flow', 'pitta+kapha'),
('seed', 'yoga', 'Include twisting poses to detoxify', 'pitta+kapha'),
('seed', 'yoga', 'Hold downward dog for 5 breaths', 'pitta+kapha'),
('seed', 'yoga', 'Practice sheetali (cooling) breathing', 'pitta+kapha'),
('seed', 'yoga', 'End with a seated meditation', 'pitta+kapha'),
('seed', 'routine', 'Wake up early before 6 AM', 'pitta+kapha'),
('seed', 'routine', 'Engage in moderate morning exercise', 'pitta+kapha'),
('seed', 'routine', 'Stay cool during the hottest part of the day', 'pitta+kapha'),
('seed', 'routine', 'Avoid afternoon naps', 'pitta+kapha'),
('seed', 'routine', 'Practice evening gratitude journaling', 'pitta+kapha'),

-- VATA+KAPHA
('seed', 'diet', 'Drink warm ginger water on waking', 'vata+kapha'),
('seed', 'diet', 'Eat warm, light, well-spiced meals', 'vata+kapha'),
('seed', 'diet', 'Avoid cold drinks and raw foods', 'vata+kapha'),
('seed', 'diet', 'Sip cinnamon tea in the afternoon', 'vata+kapha'),
('seed', 'diet', 'Have a light soup for dinner', 'vata+kapha'),
('seed', 'yoga', 'Practice slow but continuous sun salutations', 'vata+kapha'),
('seed', 'yoga', 'Include gentle backbends to open the chest', 'vata+kapha'),
('seed', 'yoga', 'Hold warrior poses for stability', 'vata+kapha'),
('seed', 'yoga', 'Practice energizing breathing for 3 minutes', 'vata+kapha'),
('seed', 'yoga', 'End with a short, warm relaxation', 'vata+kapha'),
('seed', 'routine', 'Wake up early and stretch immediately', 'vata+kapha'),
('seed', 'routine', 'Dry brush the skin to stimulate circulation', 'vata+kapha'),
('seed', 'routine', 'Keep moving throughout the day', 'vata+kapha'),
('seed', 'routine', 'Avoid getting cold or damp', 'vata+kapha'),
('seed', 'routine', 'Sleep at a consistent, early time', 'vata+kapha');
